import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "picsum.photos" },
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "**.mitiendanube.com" },
      { protocol: "https", hostname: "cdn.newgarden.com.ar" },
      { protocol: "https", hostname: "elbanquito.com.ar" },
      { protocol: "https", hostname: "d22fxaf9t8d39k.cloudfront.net" },
      { protocol: "https", hostname: "distribuidoraliliana.com.ar" },
      { protocol: "https", hostname: "**.vtexassets.com" },
      { protocol: "https", hostname: "pedidos.delicel.com.ar" },
      { protocol: "https", hostname: "naturalseed.com.ar" },
      { protocol: "https", hostname: "granerorosario.com" },
      { protocol: "https", hostname: "pampavida.com" },
      { protocol: "https", hostname: "glutenfreemarket.com.ar" },
      { protocol: "https", hostname: "www.aptomarket.com.ar" },
      { protocol: "https", hostname: "happyfood.com.ar" },
      { protocol: "https", hostname: "storage.googleapis.com" },
      { protocol: "https", hostname: "starnutrition.com.ar" },
      { protocol: "https", hostname: "cdn.farmacialeloir.com.ar" },
      { protocol: "https", hostname: "images.rappi.com.ar" },
      { protocol: "https", hostname: "purafrutta.com" },
      { protocol: "https", hostname: "dieteticaviamonte.com.ar" },
      { protocol: "https", hostname: "toogood.com.ar" },
      { protocol: "https", hostname: "acaciadietetica.com" },
      { protocol: "https", hostname: "dicomere.com.ar" },
      { protocol: "https", hostname: "yinyangargentina.com.ar" },
      { protocol: "https", hostname: "hegonatural.com" },
      { protocol: "https", hostname: "frutosare.com.ar" },
      { protocol: "https", hostname: "www.enasport.com" },
      { protocol: "https", hostname: "www.demusculos.com" },
      { protocol: "https", hostname: "wakomercadonatural.com" },
      { protocol: "https", hostname: "cdn11.bigcommerce.com" },
      { protocol: "https", hostname: "laduvalina.com.ar" },
      { protocol: "https", hostname: "aldeaecologica.com.ar" },
      { protocol: "https", hostname: "images.fravega.com" },
      { protocol: "https", hostname: "burganas.com.ar" },
      { protocol: "https", hostname: "kibou.com.ar" },
      { protocol: "https", hostname: "conosud-sa.com.ar" },
      { protocol: "https", hostname: "feliceslasvacas.com" },
    ],
  },
};

export default nextConfig;
